version: "3.7"

services:
  # openapiのclient用のコードを自動生成するコンテナ
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./src:/src
    command: generate -i http://127.0.0.1:8003/api/v1/openapi.json@ -g typescript-axios -o /src/api_clients --skip-validate-spec
